export default { 
    'Ctrl-Enter': 'editor: eval line',
    'Ctrl-/': 'editor:toggleComment',
    'Alt-Enter': 'editor: eval block',
    'Shift-Ctrl-Enter': 'editor: eval all',
    'Shift-Ctrl-G': 'gallery:shareSketch',
    'Shift-Ctrl-F': 'editor: format code',
    'Shift-Ctrl-L': 'gallery:saveToURL',
    'Shift-Ctrl-H': 'ui: hide all',
    'Shift-Ctrl-S': 'screencap',
    'Shift-Ctrl-T': 'ui: toggle toolbar',
    'Shift-Ctrl-O': 'toggleRenderAll',
    'Shift-Ctrl-1': 'editor: show buf0',
    'Shift-Ctrl-2': 'editor: show buf1',
    'Shift-Ctrl-3': 'editor: show buf2',
    'Shift-Ctrl-4': 'editor: show buf3',
    // todo: better shortcut?
    'Shift-Ctrl-Alt-1': 'renderOut0',
    'Shift-Ctrl-Alt-2': 'renderOut1',
    'Shift-Ctrl-Alt-3': 'renderOut2',
    'Shift-Ctrl-Alt-4': 'renderOut3',

    'Cmd-Enter': 'editor: eval line',
    'Cmd-/': 'editor:toggleComment',
    'Shift-Cmd-Enter': 'editor: eval all',
    'Shift-Cmd-G': 'gallery:shareSketch',
    'Shift-Cmd-F': 'editor: format code',
    'Shift-Cmd-L': 'gallery:saveToURL',
    'Shift-Cmd-H': 'ui: hide all',
    'Shift-Cmd-S': 'screencap',
    'Shift-Cmd-O': 'toggleRenderAll',
    'Shift-Cmd-1': 'editor: show buf0',
    'Shift-Cmd-2': 'editor: show buf1',
    'Shift-Cmd-3': 'editor: show buf2',
    'Shift-Cmd-4': 'editor: show buf3',
    // todo: better shortcut?
    'Shift-Cmd-Alt-1': 'renderOut0',
    'Shift-Cmd-Alt-2': 'renderOut1',
    'Shift-Cmd-Alt-3': 'renderOut2',
    'Shift-Cmd-Alt-4': 'renderOut3',
}