module.exports = { 
    'Ctrl-Enter': 'editor:evalLine',
    'Ctrl-/': 'editor:toggleComment',
    'Alt-Enter': 'editor:evalBlock',
    'Shift-Ctrl-Enter': 'editor:evalAll',
    'Shift-Ctrl-G': 'gallery:shareSketch',
    'Shift-Ctrl-F': 'editor:formatCode',
    'Shift-Ctrl-L': 'gallery:saveToURL',
    'Shift-Ctrl-H': 'hideAll',
    'Shift-Ctrl-S': 'screencap',
    'Shift-Ctrl-O': 'toggleRenderAll',
    'Shift-Ctrl-1': 'renderO0',
    'Shift-Ctrl-2': 'renderO1',
    'Shift-Ctrl-3': 'renderO2',
    'Shift-Ctrl-4': 'renderO3',

    'Cmd-Enter': 'editor:evalLine',
    'Cmd-/': 'editor:toggleComment',
    'Shift-Cmd-Enter': 'editor:evalAll',
    'Shift-Cmd-G': 'gallery:shareSketch',
    'Shift-Cmd-F': 'editor:formatCode',
    'Shift-Cmd-L': 'gallery:saveToURL',
    'Shift-Cmd-H': 'hideAll',
    'Shift-Cmd-S': 'screencap',
    'Shift-Cmd-O': 'toggleRenderAll',
    'Shift-Cmd-1': 'renderO0',
    'Shift-Cmd-2': 'renderO1',
    'Shift-Cmd-3': 'renderO2',
    'Shift-Cmd-4': 'renderO3',
}